------------------------------------------------------------------------ r2667 | wistaria | 2008-01-07 17:50:40 +0900 (Mon, 07 Jan 2008) | 1 line
------------------------------------------------------------------------

diff --git a/simple/Makefile.in b/simple/Makefile.in
--- a/simple/Makefile.in
+++ b/simple/Makefile.in
@@ -14,7 +14,6 @@
 
 @SET_MAKE@
 
-
 srcdir = @srcdir@
 top_srcdir = @top_srcdir@
 VPATH = @srcdir@
@@ -37,13 +36,10 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-subdir = check
-DIST_COMMON = $(dist_noinst_DATA) $(dist_noinst_SCRIPTS) \
-	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
-	$(srcdir)/chain.gp.in $(srcdir)/dterm.gp.in \
-	$(srcdir)/kagome.gp.in $(srcdir)/plot.gp.in \
-	$(srcdir)/site.gp.in $(srcdir)/transmag.gp.in \
-	$(srcdir)/triangle.gp.in $(srcdir)/xyz.gp.in
+check_PROGRAMS = loop$(EXEEXT)
+subdir = simple
+DIST_COMMON = $(dist_noinst_DATA) $(srcdir)/Makefile.am \
+	$(srcdir)/Makefile.in
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/acinclude.m4 \
 	$(top_srcdir)/config/ac_alps.m4 \
@@ -51,12 +47,34 @@ am__aclocal_m4_deps = $(top_srcdir)/acinclude.m4 \
 am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
 mkinstalldirs = $(install_sh) -d
-CONFIG_CLEAN_FILES = chain.gp dterm.gp kagome.gp plot.gp site.gp \
-	transmag.gp triangle.gp xyz.gp
-SCRIPTS = $(dist_noinst_SCRIPTS)
-SOURCES =
-DIST_SOURCES =
+CONFIG_CLEAN_FILES =
+am_loop_OBJECTS = loop.$(OBJEXT)
+loop_OBJECTS = $(am_loop_OBJECTS)
+loop_LDADD = $(LDADD)
+loop_DEPENDENCIES =
+depcomp = $(SHELL) $(top_srcdir)/config/depcomp
+am__depfiles_maybe = depfiles
+CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
+	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
+LTCXXCOMPILE = $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) \
+	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
+	$(AM_CXXFLAGS) $(CXXFLAGS)
+CXXLD = $(CXX)
+CXXLINK = $(LIBTOOL) --tag=CXX --mode=link $(CXXLD) $(AM_CXXFLAGS) \
+	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
+COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
+	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
+LTCOMPILE = $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) \
+	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
+	$(AM_CFLAGS) $(CFLAGS)
+CCLD = $(CC)
+LINK = $(LIBTOOL) --tag=CC --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
+	$(AM_LDFLAGS) $(LDFLAGS) -o $@
+SOURCES = $(loop_SOURCES)
+DIST_SOURCES = $(loop_SOURCES)
 DATA = $(dist_noinst_DATA)
+ETAGS = etags
+CTAGS = ctags
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 ACLOCAL = @ACLOCAL@
 AMDEP_FALSE = @AMDEP_FALSE@
@@ -191,30 +209,14 @@ sbindir = @sbindir@
 sharedstatedir = @sharedstatedir@
 sysconfdir = @sysconfdir@
 target_alias = @target_alias@
-dist_noinst_SCRIPTS = run-test.sh
-
-#
-
-#
-
-#
-
-#
-
-#
-
-#
-
-#
-dist_noinst_DATA = plot-energy plot-sheat plot-m plot-m2 plot-sus \
-	plot-sm plot-sm2 plot-ssus plot-tm plot-sign chain-1 chain-2 \
-	chain-3 chain-4 chain-5 dterm-1 dterm-2 dterm-3 kagome-1 \
-	kagome-2 kagome-3 kagome-4 site-1 site-2 site-3 site-4 site-5 \
-	transmag-1 transmag-2 transmag-3 transmag-4 triangle-1 \
-	triangle-2 triangle-3 triangle-4 xyz-1 xyz-2 xyz-3 xyz-4 xyz-5
+dist_noinst_DATA = loop.op
+loop_SOURCES = loop.C observable.h options.h
+TESTS = $(check_PROGRAMS)
+TESTS_ENVIRONMENT = $(top_srcdir)/config/run-test $(srcdir)
 all: all-am
 
 .SUFFIXES:
+.SUFFIXES: .C .lo .o .obj
 $(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am  $(am__configure_deps)
 	@for dep in $?; do \
 	  case '$(am__configure_deps)' in \
@@ -224,9 +226,9 @@ $(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am  $(am__confi
 	      exit 1;; \
 	  esac; \
 	done; \
-	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  check/Makefile'; \
+	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  simple/Makefile'; \
 	cd $(top_srcdir) && \
-	  $(AUTOMAKE) --foreign  check/Makefile
+	  $(AUTOMAKE) --foreign  simple/Makefile
 .PRECIOUS: Makefile
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	@case '$?' in \
@@ -244,22 +246,45 @@ $(top_srcdir)/configure: @MAINTAINER_MODE_TRUE@ $(am__configure_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 $(ACLOCAL_M4): @MAINTAINER_MODE_TRUE@ $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
-chain.gp: $(top_builddir)/config.status $(srcdir)/chain.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
-dterm.gp: $(top_builddir)/config.status $(srcdir)/dterm.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
-kagome.gp: $(top_builddir)/config.status $(srcdir)/kagome.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
-plot.gp: $(top_builddir)/config.status $(srcdir)/plot.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
-site.gp: $(top_builddir)/config.status $(srcdir)/site.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
-transmag.gp: $(top_builddir)/config.status $(srcdir)/transmag.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
-triangle.gp: $(top_builddir)/config.status $(srcdir)/triangle.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
-xyz.gp: $(top_builddir)/config.status $(srcdir)/xyz.gp.in
-	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
+
+clean-checkPROGRAMS:
+	@list='$(check_PROGRAMS)'; for p in $$list; do \
+	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
+	  echo " rm -f $$p $$f"; \
+	  rm -f $$p $$f ; \
+	done
+loop$(EXEEXT): $(loop_OBJECTS) $(loop_DEPENDENCIES) 
+	@rm -f loop$(EXEEXT)
+	$(CXXLINK) $(loop_LDFLAGS) $(loop_OBJECTS) $(loop_LDADD) $(LIBS)
+
+mostlyclean-compile:
+	-rm -f *.$(OBJEXT)
+
+distclean-compile:
+	-rm -f *.tab.c
+
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/loop.Po@am__quote@
+
+.C.o:
+@am__fastdepCXX_TRUE@	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
+@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='$<' object='$@' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCXX_FALSE@	$(CXXCOMPILE) -c -o $@ $<
+
+.C.obj:
+@am__fastdepCXX_TRUE@	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
+@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='$<' object='$@' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCXX_FALSE@	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`
+
+.C.lo:
+@am__fastdepCXX_TRUE@	if $(LTCXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
+@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Plo"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='$<' object='$@' libtool=yes @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCXX_FALSE@	$(LTCXXCOMPILE) -c -o $@ $<
 
 mostlyclean-libtool:
 	-rm -f *.lo
@@ -270,12 +295,127 @@ clean-libtool:
 distclean-libtool:
 	-rm -f libtool
 uninstall-info-am:
+
+ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
+	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
+	unique=`for i in $$list; do \
+	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
+	  done | \
+	  $(AWK) '    { files[$$0] = 1; } \
+	       END { for (i in files) print i; }'`; \
+	mkid -fID $$unique
 tags: TAGS
-TAGS:
 
+TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
+		$(TAGS_FILES) $(LISP)
+	tags=; \
+	here=`pwd`; \
+	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
+	unique=`for i in $$list; do \
+	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
+	  done | \
+	  $(AWK) '    { files[$$0] = 1; } \
+	       END { for (i in files) print i; }'`; \
+	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
+	  test -n "$$unique" || unique=$$empty_fix; \
+	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
+	    $$tags $$unique; \
+	fi
 ctags: CTAGS
-CTAGS:
+CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
+		$(TAGS_FILES) $(LISP)
+	tags=; \
+	here=`pwd`; \
+	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
+	unique=`for i in $$list; do \
+	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
+	  done | \
+	  $(AWK) '    { files[$$0] = 1; } \
+	       END { for (i in files) print i; }'`; \
+	test -z "$(CTAGS_ARGS)$$tags$$unique" \
+	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
+	     $$tags $$unique
 
+GTAGS:
+	here=`$(am__cd) $(top_builddir) && pwd` \
+	  && cd $(top_srcdir) \
+	  && gtags -i $(GTAGS_ARGS) $$here
+
+distclean-tags:
+	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
+
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
+	srcdir=$(srcdir); export srcdir; \
+	list='$(TESTS)'; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xpass=`expr $$xpass + 1`; \
+		failed=`expr $$failed + 1`; \
+		echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+		echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xfail=`expr $$xfail + 1`; \
+		echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+		failed=`expr $$failed + 1`; \
+		echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    else \
+	      skip=`expr $$skip + 1`; \
+	      echo "SKIP: $$tst"; \
+	    fi; \
+	  done; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="All $$all tests passed"; \
+	    else \
+	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all tests failed"; \
+	    else \
+	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    fi; \
+	  fi; \
+	  dashes="$$banner"; \
+	  skipped=""; \
+	  if test "$$skip" -ne 0; then \
+	    skipped="($$skip tests were not run)"; \
+	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$skipped"; \
+	  fi; \
+	  report=""; \
+	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$report"; \
+	  fi; \
+	  dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  test -z "$$skipped" || echo "$$skipped"; \
+	  test -z "$$report" || echo "$$report"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
 
 distdir: $(DISTFILES)
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
@@ -305,8 +445,10 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
-all-am: Makefile $(SCRIPTS) $(DATA)
+all-am: Makefile $(DATA)
 installdirs:
 install: install-am
 install-exec: install-exec-am
@@ -334,11 +476,14 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-am
 
-clean-am: clean-generic clean-libtool clean-local mostlyclean-am
+clean-am: clean-checkPROGRAMS clean-generic clean-libtool \
+	mostlyclean-am
 
 distclean: distclean-am
+	-rm -rf ./$(DEPDIR)
 	-rm -f Makefile
-distclean-am: clean-am distclean-generic distclean-libtool
+distclean-am: clean-am distclean-compile distclean-generic \
+	distclean-libtool distclean-tags
 
 dvi: dvi-am
 
@@ -361,12 +506,14 @@ install-man:
 installcheck-am:
 
 maintainer-clean: maintainer-clean-am
+	-rm -rf ./$(DEPDIR)
 	-rm -f Makefile
 maintainer-clean-am: distclean-am maintainer-clean-generic
 
 mostlyclean: mostlyclean-am
 
-mostlyclean-am: mostlyclean-generic mostlyclean-libtool
+mostlyclean-am: mostlyclean-compile mostlyclean-generic \
+	mostlyclean-libtool
 
 pdf: pdf-am
 
@@ -378,81 +525,21 @@ ps-am:
 
 uninstall-am: uninstall-info-am
 
-.PHONY: all all-am check check-am clean clean-generic clean-libtool \
-	clean-local distclean distclean-generic distclean-libtool \
-	distdir dvi dvi-am html html-am info info-am install \
-	install-am install-data install-data-am install-exec \
-	install-exec-am install-info install-info-am install-man \
-	install-strip installcheck installcheck-am installdirs \
-	maintainer-clean maintainer-clean-generic mostlyclean \
+.PHONY: CTAGS GTAGS all all-am check check-TESTS check-am clean \
+	clean-checkPROGRAMS clean-generic clean-libtool ctags \
+	distclean distclean-compile distclean-generic \
+	distclean-libtool distclean-tags distdir dvi dvi-am html \
+	html-am info info-am install install-am install-data \
+	install-data-am install-exec install-exec-am install-info \
+	install-info-am install-man install-strip installcheck \
+	installcheck-am installdirs maintainer-clean \
+	maintainer-clean-generic mostlyclean mostlyclean-compile \
 	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
-	uninstall uninstall-am uninstall-info-am
+	tags uninstall uninstall-am uninstall-info-am
 
 
-.PHONY : run
-
-run: chain dterm kagome site transmag triangle xyz
-.PHONY : chain
-chain:
-	(cd $(top_builddir) && $(MAKE) loop_pp)
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp chain-1 plot-energy plot-sheat plot-m2 plot-m4 plot-sus plot-sm2 plot-sm4 plot-ssus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp chain-2 plot-energy plot-sheat plot-m2 plot-m4 plot-sus plot-sm2 plot-sm4 plot-ssus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp chain-3 plot-energy plot-sheat plot-m2 plot-m4 plot-sus plot-sm2 plot-sm4 plot-ssus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp chain-4 plot-energy plot-sheat plot-m2 plot-m4 plot-sus plot-sm2 plot-sm4 plot-ssus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp chain-5 plot-energy plot-sheat plot-m2 plot-m4 plot-sus plot-sm2 plot-sm4 plot-ssus
-
-.PHONY : dterm
-
-dterm:
-	(cd $(top_builddir) && $(MAKE) loop_pp)
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp dterm-1 plot-energy plot-sheat plot-m2 plot-m4 plot-sus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp dterm-2 plot-energy plot-sheat plot-m2 plot-m4 plot-sus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp dterm-3 plot-energy plot-sheat plot-m2 plot-m4 plot-sus
-.PHONY : kagome
-kagome:
-	(cd $(top_builddir) && $(MAKE) loop_pp)
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp kagome-1 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp kagome-2 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp kagome-3 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp kagome-4 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-.PHONY : site
-site:
-	(cd $(top_builddir) && $(MAKE) loop_pp)
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp site-1 plot-energy plot-sheat plot-m plot-sus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp site-2 plot-energy plot-sheat plot-m plot-sus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp site-3 plot-energy plot-sheat plot-m plot-sus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp site-4 plot-energy plot-sheat plot-m plot-sus
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp site-5 plot-energy plot-sheat plot-m plot-sus
-.PHONY : transmag
-transmag:
-	(cd $(top_builddir)/extras/transmag && $(MAKE) transmag_pp)
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/transmag/transmag_pp transmag-1 plot-energy plot-sheat plot-tm
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/transmag/transmag_pp transmag-2 plot-energy plot-sheat plot-m
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/transmag/transmag_pp transmag-3 plot-energy plot-sheat plot-tm
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/transmag/transmag_pp transmag-4 plot-energy plot-sheat plot-sm
-.PHONY : triangle
-triangle:
-	(cd $(top_builddir) && $(MAKE) loop_pp)
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp triangle-1 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp triangle-2 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp triangle-3 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/loop_pp triangle-4 plot-energy plot-sheat plot-sus plot-m2 plot-sign plot-zeromeron plot-signmeron
-
-.PHONY : xyz
-
-xyz:
-	(cd $(top_builddir)/extras/xyz && $(MAKE) xyz_pp)
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/xyz/xyz_pp xyz-1 plot-energy plot-sheat plot-sus plot-ssus plot-m2
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/xyz/xyz_pp xyz-2 plot-energy plot-sheat plot-sus plot-ssus plot-m2
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/xyz/xyz_pp xyz-3 plot-energy plot-sheat plot-sus plot-ssus plot-m2
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/xyz/xyz_pp xyz-4 plot-energy plot-sheat plot-sus plot-ssus plot-m2
-	$(SHELL) $(srcdir)/run-test.sh $(top_builddir)/extras/xyz/xyz_pp xyz-5 plot-energy plot-sheat plot-sus plot-ssus plot-m2
-
-#
-
-clean-local :
-	rm -rf *.run
-	rm -f *.dat *.db *.text
+.PHONY : test tests
+test tests : check
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
