------------------------------------------------------------------------ r2623 | wistaria | 2007-11-19 19:46:42 +0900 (Mon, 19 Nov 2007) | 1 line
------------------------------------------------------------------------

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -5,25 +5,31 @@ if test "$1" == '--skip-check'; then
   force_version=no
 fi
 
-# required version of autotools
-am_require=1.9.6
-ac_require=2.59
-lt_require=1.5.22
-if `(glibtoolize --version) > /dev/null 2>&1`; then
-  LIBTOOLIZE=glibtoolize
-else
-  LIBTOOLIZE=libtoolize
-fi
-
 if test -f configure.ac; then :; else
   echo "Error: configure.ac not found." 1>&2
   exit -1
 fi
 
+# required version of autotools
+am_require=1.9.6
+ac_require=2.59
+lt_require=1.5.22
+if `(grep AC_PROG_LIBTOOL configure.ac) > /dev/null 2>&1`; then
+  if `(glibtoolize --version) > /dev/null 2>&1`; then
+    LIBTOOLIZE=glibtoolize
+  else
+    LIBTOOLIZE=libtoolize
+  fi
+else
+  LIBTOOLIZE=
+fi
+
 if test "x$force_version" = xyes; then
   am_version=`automake --version 2>&1 | head -1 | cut -d ' ' -f 4`
   ac_version=`autoconf --version 2>&1 | head -1 | cut -d ' ' -f 4`
-  lt_version=`$LIBTOOLIZE --version 2>&1 | head -1 | cut -d ' ' -f 4`
+  if test -n "$LIBTOOLIZE"; then
+    lt_version=`$LIBTOOLIZE --version 2>&1 | head -1 | cut -d ' ' -f 4`
+  fi
 
   have_autotools=yes
   if test "x$am_version" != "x$am_require"; then
@@ -34,9 +40,11 @@ if test "x$force_version" = xyes; then
     echo "Error: autoconf version $ac_require is required, but found $ac_version." 1>&2
     have_autotools=no
   fi
-  if test "x$lt_version" != "x$lt_require"; then
-    echo "Error: libtool version $lt_require is required, but found $lt_version." 1>&2
-    have_autotools=no
+  if test -n "$LIBTOOLIZE"; then
+    if test "x$lt_version" != "x$lt_require"; then
+      echo "Error: libtool version $lt_require is required, but found $lt_version." 1>&2
+      have_autotools=no
+    fi
   fi
   if test "$have_autotools" = no; then
     exit -1
@@ -51,9 +59,11 @@ echo aclocal $aclocal_flags
      aclocal $aclocal_flags
 [ "$?" -ne 0 ] && exit $?
 
-echo $LIBTOOLIZE --force --copy
-     $LIBTOOLIZE --force --copy
-[ "$?" -ne 0 ] && exit $?
+if test -n "$LIBTOOLIZE"; then
+  echo $LIBTOOLIZE --force --copy
+       $LIBTOOLIZE --force --copy
+  [ "$?" -ne 0 ] && exit $?
+fi
 
 CONFIG_H=`find . -name config.h.in`
 for c in $CONFIG_H; do
