------------------------------------------------------------------------ r2324 | wistaria | 2006-11-10 10:44:06 +0900 (Fri, 10 Nov 2006) | 2 lines
*** empty log message ***

------------------------------------------------------------------------

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -11,7 +11,7 @@ ac_require=2.59
 lt_require=1.5.22
 
 if test -f configure.ac; then :; else
-  echo "configure.ac not found.  Stop."
+  echo "Error: configure.ac not found." 1>&2
   exit -1
 fi
 
@@ -22,19 +22,18 @@ if test "x$force_version" = xyes; then
 
   have_autotools=yes
   if test "x$am_version" != "x$am_require"; then
-    echo "Error: automake version $am_require is required, but found $am_version."
+    echo "Error: automake version $am_require is required, but found $am_version." 1>&2
     have_autotools=no
   fi
   if test "x$ac_version" != "x$ac_require"; then
-    echo "Error: autoconf version $ac_require is required, but found $ac_version."
+    echo "Error: autoconf version $ac_require is required, but found $ac_version." 1>&2
     have_autotools=no
   fi
   if test "x$lt_version" != "x$lt_require"; then
-    echo "Error: libtool version $lt_require is required, but found $lt_version."
+    echo "Error: libtool version $lt_require is required, but found $lt_version." 1>&2
     have_autotools=no
   fi
   if test "$have_autotools" = no; then
-    echo "Stop."
     exit -1
   fi
 fi
