------------------------------------------------------------------------ r1762 | wistaria | 2005-08-31 11:35:05 +0900 (Wed, 31 Aug 2005) | 2 lines
*** empty log message ***

------------------------------------------------------------------------

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,45 +1,64 @@
 #!/bin/sh
 
+force_version=yes
+if test "$1" == '--skip-check'; then
+  force_version=no
+fi
+
+# required version of autotools
+am_require=1.9.6
+ac_require=2.59
+lt_require=1.5.18
+
 if test -f configure.ac; then :; else
   echo "configure.ac not found.  Stop."
   exit -1
 fi
 
-# required version of autotools
-am_require=1.9.5
-ac_require=2.59
-lt_require=1.5.18
+if test "x$force_version" = xyes; then
+  am_version=`automake --version 2>&1 | head -1 | cut -d ' ' -f 4`
+  ac_version=`autoconf --version 2>&1 | head -1 | cut -d ' ' -f 4`
+  lt_version=`libtoolize --version 2>&1 | head -1 | cut -d ' ' -f 4`
 
-am_version=`automake --version 2>&1 | head -1 | cut -d ' ' -f 4`
-ac_version=`autoconf --version 2>&1 | head -1 | cut -d ' ' -f 4`
-lt_version=`libtoolize --version 2>&1 | head -1 | cut -d ' ' -f 4`
-
-have_autotools=yes
-if test "x$am_version" != "x$am_require"; then
-  echo "Error: automake version $am_require is required, but found $am_version."
-  have_autotools=no
-fi
-if test "x$ac_version" != "x$ac_require"; then
-  echo "Error: autoconf version $ac_require is required, but found $ac_version."
-  have_autotools=no
-fi
-if test "x$lt_version" != "x$lt_require"; then
-  echo "Error: libtool version $lt_require is required, but found $lt_version."
-  have_autotools=no
-fi
-if test "$have_autotools" = no; then
-  echo "Stop."
-  exit -1
+  have_autotools=yes
+  if test "x$am_version" != "x$am_require"; then
+    echo "Error: automake version $am_require is required, but found $am_version."
+    have_autotools=no
+  fi
+  if test "x$ac_version" != "x$ac_require"; then
+    echo "Error: autoconf version $ac_require is required, but found $ac_version."
+    have_autotools=no
+  fi
+  if test "x$lt_version" != "x$lt_require"; then
+    echo "Error: libtool version $lt_require is required, but found $lt_version."
+    have_autotools=no
+  fi
+  if test "$have_autotools" = no; then
+    echo "Stop."
+    exit -1
+  fi
 fi
 
 if test -d config; then
   aclocal_flags='-I config'
 fi
 
-set -x
-aclocal $aclocal_flags
-libtoolize --force --copy
+echo aclocal $aclocal_flags
+     aclocal $aclocal_flags
+[ "$?" -ne 0 ] && exit $?
+
+echo libtoolize --force --copy
+     libtoolize --force --copy
+[ "$?" -ne 0 ] && exit $?
+
 find . -name config.h.in | xargs touch
-automake --foreign --add-missing --copy
-autoconf
+
+echo automake --foreign --add-missing --copy
+     automake --foreign --add-missing --copy
+[ "$?" -ne 0 ] && exit $?
+
+echo autoconf
+     autoconf
+[ "$?" -ne 0 ] && exit $?
+
 rm -rf autom4te.cache
