------------------------------------------------------------------------ r870 | wistaria | 2004-06-02 12:23:31 +0900 (Wed, 02 Jun 2004) | 2 lines
*** empty log message ***

------------------------------------------------------------------------

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21610,6 +21610,7 @@ fi
 
 
 
+
 # Check whether --with-bindings or --without-bindings was given.
 if test "${with_bindings+set}" = set; then
   withval="$with_bindings"
@@ -21641,7 +21642,7 @@ echo $ECHO_N "checking for Boost uBLAS bindings library... $ECHO_C" >&6
       bindings_dir=no
       for d in $HOME $HOME/src $prefix $prefix/src /usr/local /usr/local/src
       do
-        for s in bindings ublas_bindings boost-sandbox bindings_2003_09_11
+        for s in boost-sandbox boost-bindings bindings ublas_bindings
         do
           if test -f "$d/$s/boost/numeric/bindings/lapack/lapack.hpp"; then
             found=yes
@@ -21671,6 +21672,172 @@ _ACEOF
     ac_cv_have_bindings=no
     ac_cv_bindings_dir=
     BINDINGS_CPPFLAGS=
+  fi
+
+  if test "$ac_cv_have_bindings" = yes; then
+
+
+    ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    ac_save_CPPFLAGS="$CPPFLAGS"
+    CPPFLAGS="$CPPFLAGS $BINDINGS_CPPFLAGS"
+    if test "${ac_cv_header_boost_numeric_bindings_lapack_syev_hpp+set}" = set; then
+  echo "$as_me:$LINENO: checking for boost/numeric/bindings/lapack/syev.hpp" >&5
+echo $ECHO_N "checking for boost/numeric/bindings/lapack/syev.hpp... $ECHO_C" >&6
+if test "${ac_cv_header_boost_numeric_bindings_lapack_syev_hpp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_boost_numeric_bindings_lapack_syev_hpp" >&5
+echo "${ECHO_T}$ac_cv_header_boost_numeric_bindings_lapack_syev_hpp" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking boost/numeric/bindings/lapack/syev.hpp usability" >&5
+echo $ECHO_N "checking boost/numeric/bindings/lapack/syev.hpp usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <boost/numeric/bindings/lapack/syev.hpp>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking boost/numeric/bindings/lapack/syev.hpp presence" >&5
+echo $ECHO_N "checking boost/numeric/bindings/lapack/syev.hpp presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/numeric/bindings/lapack/syev.hpp>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp: present but cannot be compiled" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/numeric/bindings/lapack/syev.hpp: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: boost/numeric/bindings/lapack/syev.hpp: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## --------------------------------- ##
+## Report this to the looper lists.  ##
+## --------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for boost/numeric/bindings/lapack/syev.hpp" >&5
+echo $ECHO_N "checking for boost/numeric/bindings/lapack/syev.hpp... $ECHO_C" >&6
+if test "${ac_cv_header_boost_numeric_bindings_lapack_syev_hpp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_boost_numeric_bindings_lapack_syev_hpp=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_boost_numeric_bindings_lapack_syev_hpp" >&5
+echo "${ECHO_T}$ac_cv_header_boost_numeric_bindings_lapack_syev_hpp" >&6
+
+fi
+
+
+    CPPFLAGS="$ac_save_CPPFLAGS"
+    ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+    if test "$ac_cv_header_boost_numeric_bindings_lapack_syev_hpp" = yes; then
+      cat >>confdefs.h <<\_ACEOF
+#define HAVE_BOOST_NUMERIC_BINDINGS_LAPACK_SYEV_HPP 1
+_ACEOF
+
+    fi
   fi
 
 
