------------------------------------------------------------------------ r1105 | wistaria | 2004-08-19 18:21:24 +0900 (Thu, 19 Aug 2004) | 2 lines
*** empty log message ***

------------------------------------------------------------------------

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1053,6 +1053,7 @@ Optional Packages:
   --with-lapack=LIBS      use LAPACK library
   --with-lapack-dir=DIR   LAPACK lib directory
   --with-mkl=PROC         use Intel Math Kernel Library (PROC=p3, p4, itp)
+  --with-mkl-dir=DIR      MKL lib directory
   --with-scsl             use SGI SCSL Scientific Library
   --with-essl             use ESSL library on IBM AIX
   --with-veclib           use vecLib framework on Mac OS X
@@ -4181,7 +4182,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4184 "configure"' > conftest.$ac_ext
+  echo '#line 4185 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5289,7 +5290,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5292:" \
+echo "$as_me:5293:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6323,11 +6324,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6326: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6327: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6330: \$? = $ac_status" >&5
+   echo "$as_me:6331: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6556,11 +6557,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6559: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6560: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6563: \$? = $ac_status" >&5
+   echo "$as_me:6564: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6616,11 +6617,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6619: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6620: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6623: \$? = $ac_status" >&5
+   echo "$as_me:6624: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8800,7 +8801,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8803 "configure"
+#line 8804 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8898,7 +8899,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8901 "configure"
+#line 8902 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11077,11 +11078,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11080: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11081: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11084: \$? = $ac_status" >&5
+   echo "$as_me:11085: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11137,11 +11138,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11140: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11141: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11144: \$? = $ac_status" >&5
+   echo "$as_me:11145: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12498,7 +12499,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12501 "configure"
+#line 12502 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12596,7 +12597,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12599 "configure"
+#line 12600 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13423,11 +13424,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13426: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13427: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13430: \$? = $ac_status" >&5
+   echo "$as_me:13431: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13483,11 +13484,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13486: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13487: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13490: \$? = $ac_status" >&5
+   echo "$as_me:13491: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15517,11 +15518,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15520: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15521: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15524: \$? = $ac_status" >&5
+   echo "$as_me:15525: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15750,11 +15751,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15753: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15754: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15757: \$? = $ac_status" >&5
+   echo "$as_me:15758: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15810,11 +15811,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15813: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15814: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15817: \$? = $ac_status" >&5
+   echo "$as_me:15818: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17994,7 +17995,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17997 "configure"
+#line 17998 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18092,7 +18093,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18095 "configure"
+#line 18096 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19157,6 +19158,8 @@ fi
 
 
 
+
+
 # Check whether --with-atlas or --without-atlas was given.
 if test "${with_atlas+set}" = set; then
   withval="$with_atlas"
@@ -19265,10 +19268,17 @@ if test "${with_mkl+set}" = set; then
           ;;
         *)
           mkl=yes
-          mkl_proc="p4"
+          mkl_proc=
       esac
     fi
 
+
+fi;
+
+# Check whether --with-mkl-dir or --without-mkl-dir was given.
+if test "${with_mkl_dir+set}" = set; then
+  withval="$with_mkl_dir"
+  mkl_dir=`echo "$withval" | sed 's,//*,/,g' | sed 's,/$,,'`
 
 fi;
 
@@ -19313,6 +19323,42 @@ if test "${with_veclib+set}" = set; then
 
 
 fi;
+
+  if test -n "$atlas_dir"; then
+    if test "x$atlas" = xno; then
+      { { echo "$as_me:$LINENO: error: inconsistent options for ATLAS library." >&5
+echo "$as_me: error: inconsistent options for ATLAS library." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    atlas=yes
+  fi
+
+  if test -n "$blas_dir"; then
+    if test "x$blas" = xno; then
+      { { echo "$as_me:$LINENO: error: inconsistent options for BLAS library." >&5
+echo "$as_me: error: inconsistent options for BLAS library." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    blas=yes
+  fi
+
+  if test -n "$lapack_dir"; then
+    if test "x$lapack" = xno; then
+      { { echo "$as_me:$LINENO: error: inconsistent options for LAPACK library." >&5
+echo "$as_me: error: inconsistent options for LAPACK library." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    lapack=yes
+  fi
+
+  if test -n "$mkl_dir"; then
+    if test "x$mkl" = xno; then
+      { { echo "$as_me:$LINENO: error: inconsistent options for MKL library." >&5
+echo "$as_me: error: inconsistent options for MKL library." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    mkl=yes
+  fi
 
   if test "x$atlas" = xyes; then
     if test "x$blas" = xyes; then
@@ -19447,79 +19493,107 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
       { echo "$as_me:$LINENO: checking for Math Kernel Library" >&5
 echo "$as_me: checking for Math Kernel Library" >&6;}
-      mkl_basedir=
-      if test -d "/opt/intel/mkl61"; then
-        mkl_basedir=/opt/intel/mkl61
-        echo "$as_me:$LINENO: checking MKL directory" >&5
+      echo "$as_me:$LINENO: checking MKL directory" >&5
 echo $ECHO_N "checking MKL directory... $ECHO_C" >&6
-        echo "$as_me:$LINENO: result: $mkl_basedir" >&5
-echo "${ECHO_T}$mkl_basedir" >&6
-      elif test -d "/opt/intel/mkl"; then
-        mkl_basedir=/opt/intel/mkl
-        echo "$as_me:$LINENO: checking MKL directory" >&5
-echo $ECHO_N "checking MKL directory... $ECHO_C" >&6
-        echo "$as_me:$LINENO: result: $mkl_basedir" >&5
-echo "${ECHO_T}$mkl_basedir" >&6
+      if test -z "$mkl_dir"; then
+        if test -d "/opt/intel/mkl70"; then
+          mkl_dir=/opt/intel/mkl70
+          echo "$as_me:$LINENO: result: $mkl_dir" >&5
+echo "${ECHO_T}$mkl_dir" >&6
+        elif test -d "/opt/intel/mkl61"; then
+          mkl_dir=/opt/intel/mkl61
+          echo "$as_me:$LINENO: result: $mkl_dir" >&5
+echo "${ECHO_T}$mkl_dir" >&6
+        elif test -d "/opt/intel/mkl"; then
+          mkl_dir=/opt/intel/mkl
+          echo "$as_me:$LINENO: result: $mkl_dir" >&5
+echo "${ECHO_T}$mkl_dir" >&6
+        else
+          echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+        fi
+      else
+        if test -d "$mkl_dir"; then
+          echo "$as_me:$LINENO: result: $mkl_dir" >&5
+echo "${ECHO_T}$mkl_dir" >&6
+        else
+          echo "$as_me:$LINENO: result: $not found" >&5
+echo "${ECHO_T}$not found" >&6
+          { { echo "$as_me:$LINENO: error: MKL directory not found." >&5
+echo "$as_me: error: MKL directory not found." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
       fi
 
+      if test -z "$mkl_proc"; then
+        case "x$host_cpu" in
+        xi686)
+          mkl_proc="p4"
+          ;;
+        xia64)
+          mkl_proc="itp"
+          ;;
+        *)
+          ;;
+        esac
+      fi
+
+      echo "$as_me:$LINENO: checking for processor type" >&5
+echo $ECHO_N "checking for processor type... $ECHO_C" >&6
       case "x$mkl_proc" in
       xp3)
         mkl_procname="Pentium 3"
-        mkl_dir="32"
+        mkl_bits="32"
         mkl_lib="mkl_p3"
-        echo "$as_me:$LINENO: checking for processor type" >&5
-echo $ECHO_N "checking for processor type... $ECHO_C" >&6
         echo "$as_me:$LINENO: result: $mkl_procname" >&5
 echo "${ECHO_T}$mkl_procname" >&6
         ;;
       xp4)
         mkl_procname="Pentium 4"
-        mkl_dir="32"
+        mkl_bits="32"
         mkl_lib="mkl_p4"
-        echo "$as_me:$LINENO: checking for processor type" >&5
-echo $ECHO_N "checking for processor type... $ECHO_C" >&6
         echo "$as_me:$LINENO: result: $mkl_procname" >&5
 echo "${ECHO_T}$mkl_procname" >&6
         ;;
       xitp)
         mkl_procname="Itanium"
-        mkl_dir="64"
+        mkl_bits="64"
         mkl_lib="mkl_itp"
-        echo "$as_me:$LINENO: checking for processor type" >&5
-echo $ECHO_N "checking for processor type... $ECHO_C" >&6
         echo "$as_me:$LINENO: result: $mkl_procname" >&5
 echo "${ECHO_T}$mkl_procname" >&6
         ;;
       *)
-        mkl_procname="Pentium 4"
-        mkl_dir="32"
-        mkl_lib="mkl_p4"
+        mkl_proc=
+        echo "$as_me:$LINENO: result: unknown processor type" >&5
+echo "${ECHO_T}unknown processor type" >&6
       esac
-      if test "$mkl_dir" = "32"; then
-        if test -f "$mkl_basedir/lib/$mkl_dir/libmkl_ia32.a"; then
-          # version 6
-          mkl_lib="mkl_ia32"
+
+      if test -n "$mkl_proc"; then
+        if test "$mkl_bits" = "32"; then
+          if test -f "$mkl_dir/lib/$mkl_bits/libmkl_ia32.a"; then
+            # version 6.1 & 7
+            mkl_lib="mkl_ia32"
+          fi
         fi
-      fi
-      if test "$mkl_dir" = "64"; then
-        if test -f "$mkl_basedir/lib/$mkl_dir/libmkl_ipf.a"; then
-          # version 6
-          mkl_lib="mkl_ipf"
+        if test "$mkl_bits" = "64"; then
+          if test -f "$mkl_dir/lib/$mkl_bits/libmkl_ipf.a"; then
+            # version 6.1 & 7
+            mkl_lib="mkl_ipf"
+          fi
         fi
-      fi
 
-      if test -d "$mkl_basedir/lib/$mkl_dir"; then
-        mkl_ldflags="-L$mkl_basedir/lib/$mkl_dir"
-      else
-        mkl_ldflags=
-      fi
-      LDFLAGS="$mkl_ldflags $ac_save_LDFLAGS"
+        if test -d "$mkl_dir/lib/$mkl_bits"; then
+          mkl_ldflags="-L$mkl_dir/lib/$mkl_bits"
+        else
+          mkl_ldflags=
+        fi
+        LDFLAGS="$mkl_ldflags $ac_save_LDFLAGS"
 
-      mkl_libs=
-      found=no
+        mkl_libs=
+        found=no
 
-      if test "$mkl_proc" != "itp"; then
-        echo "$as_me:$LINENO: checking for d_abs" >&5
+        if test "$mkl_proc" != "itp"; then
+          echo "$as_me:$LINENO: checking for d_abs" >&5
 echo $ECHO_N "checking for d_abs... $ECHO_C" >&6
 if test "${ac_cv_func_d_abs+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19754,7 +19828,7 @@ fi
 
 fi
 
-        echo "$as_me:$LINENO: checking for omp_in_parallel_ in -lguide" >&5
+          echo "$as_me:$LINENO: checking for omp_in_parallel_ in -lguide" >&5
 echo $ECHO_N "checking for omp_in_parallel_ in -lguide... $ECHO_C" >&6
 if test "${ac_cv_lib_guide_omp_in_parallel_+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19820,8 +19894,8 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_guide_omp_in_parallel_" >&5
 echo "${ECHO_T}$ac_cv_lib_guide_omp_in_parallel_" >&6
 if test $ac_cv_lib_guide_omp_in_parallel_ = yes; then
   mkl_libs="-lguide $mkl_libs"
-           LIBS="$mkl_libs $ac_save_LIBS"
-           as_ac_Lib=`echo "ac_cv_lib_$mkl_lib''_dgemm_" | $as_tr_sh`
+             LIBS="$mkl_libs $ac_save_LIBS"
+             as_ac_Lib=`echo "ac_cv_lib_$mkl_lib''_dgemm_" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for dgemm_ in -l$mkl_lib" >&5
 echo $ECHO_N "checking for dgemm_ in -l$mkl_lib... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Lib+set}\" = set"; then
@@ -19888,8 +19962,8 @@ echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
   mkl_libs="-l$mkl_lib $mkl_libs"
-             LIBS="$mkl_libs $ac_save_LIBS"
-             echo "$as_me:$LINENO: checking for dsyev_ in -lmkl_lapack" >&5
+               LIBS="$mkl_libs $ac_save_LIBS"
+               echo "$as_me:$LINENO: checking for dsyev_ in -lmkl_lapack" >&5
 echo $ECHO_N "checking for dsyev_ in -lmkl_lapack... $ECHO_C" >&6
 if test "${ac_cv_lib_mkl_lapack_dsyev_+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19964,8 +20038,8 @@ fi
 
 fi
 
-      else
-        echo "$as_me:$LINENO: checking for d_abs" >&5
+        else
+          echo "$as_me:$LINENO: checking for d_abs" >&5
 echo $ECHO_N "checking for d_abs... $ECHO_C" >&6
 if test "${ac_cv_func_d_abs+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20200,7 +20274,7 @@ fi
 
 fi
 
-        echo "$as_me:$LINENO: checking for f_concat" >&5
+          echo "$as_me:$LINENO: checking for f_concat" >&5
 echo $ECHO_N "checking for f_concat... $ECHO_C" >&6
 if test "${ac_cv_func_f_concat+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20365,7 +20439,7 @@ fi
 
 fi
 
-        echo "$as_me:$LINENO: checking for omp_in_parallel_ in -lguide" >&5
+          echo "$as_me:$LINENO: checking for omp_in_parallel_ in -lguide" >&5
 echo $ECHO_N "checking for omp_in_parallel_ in -lguide... $ECHO_C" >&6
 if test "${ac_cv_lib_guide_omp_in_parallel_+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20431,8 +20505,8 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_guide_omp_in_parallel_" >&5
 echo "${ECHO_T}$ac_cv_lib_guide_omp_in_parallel_" >&6
 if test $ac_cv_lib_guide_omp_in_parallel_ = yes; then
   mkl_libs="-lguide $mkl_libs"
-           LIBS="$mkl_libs $ac_save_LIBS"
-           as_ac_Lib=`echo "ac_cv_lib_$mkl_lib''_dgemm_" | $as_tr_sh`
+             LIBS="$mkl_libs $ac_save_LIBS"
+             as_ac_Lib=`echo "ac_cv_lib_$mkl_lib''_dgemm_" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for dgemm_ in -l$mkl_lib" >&5
 echo $ECHO_N "checking for dgemm_ in -l$mkl_lib... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Lib+set}\" = set"; then
@@ -20499,8 +20573,8 @@ echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
   mkl_libs="-l$mkl_lib $mkl_libs"
-             LIBS="$mkl_libs $ac_save_LIBS"
-             echo "$as_me:$LINENO: checking for dsyev_ in -lmkl_lapack" >&5
+               LIBS="$mkl_libs $ac_save_LIBS"
+               echo "$as_me:$LINENO: checking for dsyev_ in -lmkl_lapack" >&5
 echo $ECHO_N "checking for dsyev_ in -lmkl_lapack... $ECHO_C" >&6
 if test "${ac_cv_lib_mkl_lapack_dsyev_+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20575,12 +20649,13 @@ fi
 
 fi
 
-      fi
-      if test "$found" = yes; then
-        LAPACK_LDFLAGS="$mkl_ldflags"
-        LAPACK_LIBS="$mkl_libs"
-        found_blas=yes
-        found_lapack=yes
+        fi
+        if test "$found" = yes; then
+          LAPACK_LDFLAGS="$mkl_ldflags"
+          LAPACK_LIBS="$mkl_libs"
+          found_blas=yes
+          found_lapack=yes
+        fi
       fi
     fi
     if test "x$mkl" = xyes; then
