------------------------------------------------------------------------ r705 | wistaria | 2004-03-18 10:16:30 +0900 (Thu, 18 Mar 2004) | 2 lines
*** empty log message ***

------------------------------------------------------------------------

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1714,16 +1714,16 @@ _ACEOF
 echo "$as_me: starting configuration for ALPS/looper version $PACKAGE_VERSION ($looper_date)" >&6;}
 
 
-echo "$as_me:$LINENO: checking for ALPS library" >&5
-echo $ECHO_N "checking for ALPS library... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for ALPS Libraries" >&5
+echo $ECHO_N "checking for ALPS Libraries... $ECHO_C" >&6
 if test -f "$ac_cv_alps_include_mk"; then
   echo "$as_me:$LINENO: result: OK" >&5
 echo "${ECHO_T}OK" >&6
 else
   echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6
-  { { echo "$as_me:$LINENO: error: ALPS library not found." >&5
-echo "$as_me: error: ALPS library not found." >&2;}
+  { { echo "$as_me:$LINENO: error: ALPS Libraries not found." >&5
+echo "$as_me: error: ALPS Libraries not found." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1733,10 +1733,10 @@ echo "$as_me:$LINENO: result: $ac_cv_alps_version" >&5
 echo "${ECHO_T}$ac_cv_alps_version" >&6
 
 if test "$ac_cv_alps_type" = "full"; then :; else
-  { echo "$as_me:$LINENO: ALPS Light Libraries are detected." >&5
-echo "$as_me: ALPS Light Libraries are detected." >&6;}
-  { { echo "$as_me:$LINENO: error: ALPS/looper requies the full version of ALPS Libraries." >&5
-echo "$as_me: error: ALPS/looper requies the full version of ALPS Libraries." >&2;}
+  { echo "$as_me:$LINENO: detected ALPS Light Libraries" >&5
+echo "$as_me: detected ALPS Light Libraries" >&6;}
+  { { echo "$as_me:$LINENO: error: ALPS/looper requies the full version of ALPS Libraries" >&5
+echo "$as_me: error: ALPS/looper requies the full version of ALPS Libraries" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
