------------------------------------------------------------------------ r2017 | wistaria | 2006-04-29 01:39:24 +0900 (Sat, 29 Apr 2006) | 2 lines
*** empty log message ***

------------------------------------------------------------------------

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL HAVE_MPI_TRUE HAVE_MPI_FALSE DEFAULT_INCLUDES LDADD CPPFLAGS_MPI LDFLAGS_MPI LIBS_MPI EXIST_CHECK_TRUE EXIST_CHECK_FALSE BUILD_CHECK_TRUE BUILD_CHECK_FALSE EXIST_EXTRAS_TRUE EXIST_EXTRAS_FALSE BUILD_EXTRAS_TRUE BUILD_EXTRAS_FALSE EXIST_TEST_TRUE EXIST_TEST_FALSE BUILD_TEST_TRUE BUILD_TEST_FALSE EXIST_V31_TRUE EXIST_V31_FALSE BUILD_V31_TRUE BUILD_V31_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL HAVE_MPI_TRUE HAVE_MPI_FALSE DEFAULT_INCLUDES LDADD CPPFLAGS_MPI LDFLAGS_MPI LIBS_MPI ENABLE_DIAG_TRUE ENABLE_DIAG_FALSE ENABLE_ISING_TRUE ENABLE_ISING_FALSE ENABLE_PI_TRUE ENABLE_PI_FALSE ENABLE_SSE_TRUE ENABLE_SSE_FALSE ENABLE_SSE_QWL_TRUE ENABLE_SSE_QWL_FALSE EXIST_CHECK_TRUE EXIST_CHECK_FALSE BUILD_CHECK_TRUE BUILD_CHECK_FALSE EXIST_EXTRAS_TRUE EXIST_EXTRAS_FALSE BUILD_EXTRAS_TRUE BUILD_EXTRAS_FALSE EXIST_TEST_TRUE EXIST_TEST_FALSE BUILD_TEST_TRUE BUILD_TEST_FALSE EXIST_V31_TRUE EXIST_V31_FALSE BUILD_V31_TRUE BUILD_V31_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1036,6 +1036,13 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --enable-all-method     enable all methods
+  --enable-diag           enable exact diagonalization method
+  --enable-ising          enable Swendsen-Wang method for classical Ising
+                          model
+  --disable-path-integral disable path integral method
+  --disable-sse           disable SSE method
+  --disable-sse-qwl       disable SSE quantum Wang-Landau method
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4201,7 +4208,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4204 "configure"' > conftest.$ac_ext
+  echo '#line 4211 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5336,7 +5343,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5339:" \
+echo "$as_me:5346:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6399,11 +6406,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6402: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6409: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6406: \$? = $ac_status" >&5
+   echo "$as_me:6413: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6667,11 +6674,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6670: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6677: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6674: \$? = $ac_status" >&5
+   echo "$as_me:6681: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6771,11 +6778,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6774: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6781: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6778: \$? = $ac_status" >&5
+   echo "$as_me:6785: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9116,7 +9123,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9119 "configure"
+#line 9126 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9216,7 +9223,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9219 "configure"
+#line 9226 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11556,11 +11563,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11559: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11566: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11563: \$? = $ac_status" >&5
+   echo "$as_me:11570: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11660,11 +11667,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11663: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11670: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11667: \$? = $ac_status" >&5
+   echo "$as_me:11674: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13230,11 +13237,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13233: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13240: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13237: \$? = $ac_status" >&5
+   echo "$as_me:13244: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13334,11 +13341,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13337: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13344: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13341: \$? = $ac_status" >&5
+   echo "$as_me:13348: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15537,11 +15544,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15540: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15547: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15544: \$? = $ac_status" >&5
+   echo "$as_me:15551: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15805,11 +15812,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15808: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15812: \$? = $ac_status" >&5
+   echo "$as_me:15819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15909,11 +15916,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15912: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15919: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15916: \$? = $ac_status" >&5
+   echo "$as_me:15923: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18633,6 +18640,113 @@ LIBS_MPI="$ac_cv_alps_libs_mpi"
 
 
 
+# Check whether --enable-all-method or --disable-all-method was given.
+if test "${enable_all_method+set}" = set; then
+  enableval="$enable_all_method"
+
+  if test "x$enableval" != "xno"; then
+    enable_diag=yes
+    enable_ising=yes
+  else
+    enable_pi=no
+    enable_sse=no
+    enable_sse_qwl=no
+  fi
+
+
+fi;
+
+# Check whether --enable-diag or --disable-diag was given.
+if test "${enable_diag+set}" = set; then
+  enableval="$enable_diag"
+  test "x$enableval" != "xno" && enable_diag=yes
+
+fi;
+test -z "$enable_diag" && enable_diag=no
+
+
+if test "$enable_diag" = yes; then
+  ENABLE_DIAG_TRUE=
+  ENABLE_DIAG_FALSE='#'
+else
+  ENABLE_DIAG_TRUE='#'
+  ENABLE_DIAG_FALSE=
+fi
+
+
+# Check whether --enable-ising or --disable-ising was given.
+if test "${enable_ising+set}" = set; then
+  enableval="$enable_ising"
+  test "x$enableval" != "xno" && enable_ising=yes
+
+fi;
+test -z "$enable_ising" && enable_ising=no
+
+
+if test "$enable_ising" = yes; then
+  ENABLE_ISING_TRUE=
+  ENABLE_ISING_FALSE='#'
+else
+  ENABLE_ISING_TRUE='#'
+  ENABLE_ISING_FALSE=
+fi
+
+
+# Check whether --enable-path-integral or --disable-path-integral was given.
+if test "${enable_path_integral+set}" = set; then
+  enableval="$enable_path_integral"
+  test "x$enableval" != "xyes" && enable_pi=no
+
+fi;
+test -z "$enable_pi" && enable_pi=yes
+
+
+if test "$enable_pi" = yes; then
+  ENABLE_PI_TRUE=
+  ENABLE_PI_FALSE='#'
+else
+  ENABLE_PI_TRUE='#'
+  ENABLE_PI_FALSE=
+fi
+
+
+# Check whether --enable-sse or --disable-sse was given.
+if test "${enable_sse+set}" = set; then
+  enableval="$enable_sse"
+  test "x$enableval" != "xyes" && enable_sse=no
+
+fi;
+test -z "$enable_sse" && enable_sse=yes
+
+
+if test "$enable_sse" = yes; then
+  ENABLE_SSE_TRUE=
+  ENABLE_SSE_FALSE='#'
+else
+  ENABLE_SSE_TRUE='#'
+  ENABLE_SSE_FALSE=
+fi
+
+
+# Check whether --enable-sse-qwl or --disable-sse-qwl was given.
+if test "${enable_sse_qwl+set}" = set; then
+  enableval="$enable_sse_qwl"
+  test "x$enableval" != "xyes" && enable_sse_qwl=no
+
+fi;
+test -z "$enable_sse_qwl" && enable_sse_qwl=yes
+
+
+if test "$enable_sse_qwl" = yes; then
+  ENABLE_SSE_QWL_TRUE=
+  ENABLE_SSE_QWL_FALSE='#'
+else
+  ENABLE_SSE_QWL_TRUE='#'
+  ENABLE_SSE_QWL_FALSE=
+fi
+
+
+
 if test -f "$srcdir/check/Makefile.in"; then
   exist_check=yes
 fi
@@ -18851,6 +18965,41 @@ if test -z "${HAVE_MPI_TRUE}" && test -z "${HAVE_MPI_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_MPI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_MPI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_DIAG_TRUE}" && test -z "${ENABLE_DIAG_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_DIAG\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_DIAG\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_ISING_TRUE}" && test -z "${ENABLE_ISING_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_ISING\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_ISING\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_PI_TRUE}" && test -z "${ENABLE_PI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_PI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_PI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_SSE_TRUE}" && test -z "${ENABLE_SSE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_SSE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_SSE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_SSE_QWL_TRUE}" && test -z "${ENABLE_SSE_QWL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_SSE_QWL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_SSE_QWL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -19519,6 +19668,16 @@ s,@LDADD@,$LDADD,;t t
 s,@CPPFLAGS_MPI@,$CPPFLAGS_MPI,;t t
 s,@LDFLAGS_MPI@,$LDFLAGS_MPI,;t t
 s,@LIBS_MPI@,$LIBS_MPI,;t t
+s,@ENABLE_DIAG_TRUE@,$ENABLE_DIAG_TRUE,;t t
+s,@ENABLE_DIAG_FALSE@,$ENABLE_DIAG_FALSE,;t t
+s,@ENABLE_ISING_TRUE@,$ENABLE_ISING_TRUE,;t t
+s,@ENABLE_ISING_FALSE@,$ENABLE_ISING_FALSE,;t t
+s,@ENABLE_PI_TRUE@,$ENABLE_PI_TRUE,;t t
+s,@ENABLE_PI_FALSE@,$ENABLE_PI_FALSE,;t t
+s,@ENABLE_SSE_TRUE@,$ENABLE_SSE_TRUE,;t t
+s,@ENABLE_SSE_FALSE@,$ENABLE_SSE_FALSE,;t t
+s,@ENABLE_SSE_QWL_TRUE@,$ENABLE_SSE_QWL_TRUE,;t t
+s,@ENABLE_SSE_QWL_FALSE@,$ENABLE_SSE_QWL_FALSE,;t t
 s,@EXIST_CHECK_TRUE@,$EXIST_CHECK_TRUE,;t t
 s,@EXIST_CHECK_FALSE@,$EXIST_CHECK_FALSE,;t t
 s,@BUILD_CHECK_TRUE@,$BUILD_CHECK_TRUE,;t t
